---
version: "2"

checks:
  method-lines:
    config:
      threshold: 50
  file-lines:
    config:
      threshold: 500
  return-statements:
    config:
      threshold: 8

plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true

exclude_patterns:
  - config/
  - vendor/
  - node_modules/
  - private/
  - public/dist/js/
  - public/dist/styles/font-awesome.css
  - public/dist/styles/normalize.css
  - src/bindata/bindata.go
