#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

cd $DIR

start() {
    docker-compose -p packet-guardian up -d
}

stop() {
    docker-compose -p packet-guardian stop
}

restart() {
    docker-compose -p packet-guardian restart pg-web
}

restart-full() {
    docker-compose -p packet-guardian restart
}

remove() {
    docker-compose -p packet-guardian down
}

logs() {
    docker logs -f pg-web
}

exec-db() {
    docker exec -it pg-database mysql -u root -ppassword
}

case $1 in
    start) start;;
    stop) stop;;
    rm) remove;;
    restart) restart;;
    restart-full) restart-full;;
    restart-log) restart && logs;;
    start-log) start && logs;;
    logs) logs;;

    exec-db) exec-db;;
esac
