name: Run tests

on:
  push:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install NPM deps
        run: yarn install

      - name: Enforce TypeScript/CSS lints
        run: yarn run lint

      - name: Test and Build TypeScript
        run: yarn run build:prod

      - name: Download go-bindata tool
        run: go install github.com/go-bindata/go-bindata/go-bindata@latest

      - name: Test and Build Server
        run: env PATH="$HOME/go/bin:$PATH" make bindata test build-cmd
